MGMT-22658: RFC 7093 Subject Key Identifier calculation method
Since OCP 4.22 uses Go 1.25 which changed [1] the way SKID is calculated
by default, OCP certs are using the new SKID method and so recert should
support it as well.

It was just a matter of adding the new method and using SHA-256 instead
of SHA-1 (and truncating to 20 bytes) when the new method is selected.

This should fix the following error:

```
Error: scanning and recertificationCaused by:
  0: processing discovered objects
  1: regenerating crypto
  2: re-signing cert at locations [
        k8s:Secret/openshift-operator-lifecycle-manager:packageserver-service-cert:/data/olmCAKey,
        k8s:APIService/cluster-scoped:v1.packages.operators.coreos.com:/spec/caBundle
     ] with subject CN=olm-selfsigned-567a2392748f2355, O=Red Hat, Inc.
  3: calculating SKID
  4: LibraryGoSha1 not supported for ecdsa keys
```

(The error is misleading because the brute force, having failed to
determine the method as RFC 5280, fell through to LibraryGoSha1, which
is non-sensical for ECDSA keys. This could probably be improved to
simply ignore the method if it doesn't apply to the key type, but this
change is urgent for now so we can do that separately.)

[1] https://github.com/golang/go/issues/71746